// Generated by Xata Codegen 0.26.7. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "forum_posts",
    columns: [
      { name: "baseChannelID", type: "string", unique: true },
      { name: "threadPostTitle", type: "string" },
      { name: "author", type: "string" },
      { name: "messages", type: "json" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type ForumPosts = InferredTypes["forum_posts"];
export type ForumPostsRecord = ForumPosts & XataRecord;

export type DatabaseSchema = {
  forum_posts: ForumPostsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Jacob-M-G-Evans-s-workspace-913r09.us-west-2.xata.sh/db/Clerk-Discord",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
